baseURL = "https://njkevlani.github.io/hst/"
theme = "hst"
enableEmoji = true
enableGitInfo = true

[params.author]
  name = "HST Theme"

[params]
  [params.postHistory]
    enabled = true
    siteGitRepo = "https://github.com/njkevlani/hst"
    contentDirRelativeToGitRepoRoot = "exampleSite/content"

[frontmatter]
  lastmod = ["lastmod", ":git"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"

[permalinks]
  blogs = "blogs/:title"

[outputs]
    section = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]

  [markup.goldmark]

    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    lineNos = true
    style = 'autumn'

