baseURL = "https://njkevlani.github.io/"
languageCode = "en-us"
title = "Nilesh Kevlani"
theme = "hst"
author = "Nilesh Kevlani"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
DefaultContentLanguage = "en"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  tag = "tags"
  blogtag = "blogtags"
  tiltag = "tiltags"

[permalinks]
  blogtags = "/blogs/tags/:slug"
  tiltags = "/tils/tags/:slug"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
