name: Build and Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    permissions:
      pages: write
      id-token: write


    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2

      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: deploy
        uses: actions/deploy-pages@v4
